name: truck_management_app
description: "A truck management app."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  dartz: ^0.10.1
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin-Bold.ttf
          style: italic

    - family: SignikaNegative
      fonts:
        - asset: assets/fonts/SignikaNegative-Regular.ttf
        - asset: assets/fonts/SignikaNegative-Bold.ttf
          weight: 700

    - family: YoungSerif
      fonts:
        - asset: assets/fonts/YoungSerif-Regular.ttf
          weight: 700
